### ISSUE TITLE
ImportError: cannot import name timezone

### ISSUE THREAD

**Issue by DrKaoliN** [django-nonrel/django-nonrel#11]
After installing `django-nonrel`, I cannot import `timezone`:

```
>>> from django.utils import timezone
Traceback (most recent call last):
File "<console>", line 1, in <module>
ImportError: cannot import name timezone
```

using ubuntu 12.04 LTS, python-2.7, django 1.4

**Comment by aburgel** [comment]
This is not the place to ask for help. Try the mailing list or stackoverflow.

**Comment by inocuo** [comment]
Django-nonrel doesn't contain timezone.py in django/utlis, i don't know
why...

You can try to download the file from the django version directly...
Here is the link
https://github.com/django/django/blob/master/django/utils/timezone.py

Good luck!!!

2012/11/30 Mihail notifications@github.com

> i

**Comment by aburgel** [comment]
Its in django 1.4, you're probably looking at django 1.3. I wouldn't just add it by hand. If you need it, upgrade to a newer version of django.
