### ISSUE TITLE
Docs are unavailable except via Wayback.

### ISSUE THREAD

**Issue by bryankaplan** [django-nonrel/django-nonrel#12]
The project description says there's documentation at http://docs.django-nonrel.org/ . That subdomain is not in DNS.

Trying its second-level domain, http://django-nonrel.org/ says MongoDB documentation can be found at http://django-mongodb.org/ . That domain has no A record.

The documentation from that site is available from the Wayback Machine. http://web.archive.org/web/20121222013356/http://django-mongodb.org/

**Comment by aburgel** [comment]
Thanks for letting us know. I've updated the project description to the correct url (www.django-nonrel.org) and the link to www.django-mongodb.org.
