### ISSUE TITLE
Model.objects.all() won't refresh after deleting an object

### ISSUE THREAD

**Issue by seddonym** [django-nonrel/django-nonrel#7]
This might be a usage issue rather than a bug, I'm not sure.  I've posted details [here](http://stackoverflow.com/questions/9079612/model-objects-all-wont-refresh-using-djangoappengine).

**Comment by aburgel** [comment]
this is most likely an eventual consistency issue. if you wait a bit, does that object disappear?

**Comment by seddonym** [comment]
Yes, as soon as I refresh the page.

**Comment by aburgel** [comment]
ok, pretty sure its an eventual consistency thing and not a bug. on appengine, if you do a regular query, then you may not see the most recent changes in the datastore. there are ways around this, but only in specific cases. Model.objects.all() is not one of those cases.

take a look at django-nonrel/djangoappengine#10 for a patch to support ancestor queries. those allow you to get strong consistency on certain queries.

**Comment by seddonym** [comment]
Thanks for this, I've had a read through.  I think I'm likely to avoid GAE for django for now unless I need something really scalable!
